services:
  api:
    build: .
    ports:
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./certs:/app/certs
      - ./Resources:/app/Resources
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/myapi.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Ae!8bfb666
      - DefaultConnection=server=db;userid=test;password=test;database=vaccineapi;port=3306

  db:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --loose-validate_password.policy=LOW
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: vaccineapi
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    platform: linux/amd64
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "8081:8080"

volumes:
  db_data: